name: CI - LogAnalyzer

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test-log-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create test log file
        run: |
          echo "[INFO] Start\n[ERROR] Crash\n[WARNING] Slow response\n[INFO] Done" > log.txt

      - name: Run log analyzer
        run: |
          python log_analyzer.py --input log.txt --output rapport.txt
          cat rapport.txt

      - name: Check report file
        run: |
          grep "INFO: 2" rapport.txt
          grep "ERROR: 1" rapport.txt
          grep "WARNING: 1" rapport.txt
