name: CI - LogAnalyzer

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test-log-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Aller dans le dossier log-analyzer
        run: cd log-analyzer
        shell: bash

      - name: Installer les dépendances
        run: |
          cd log-analyzer
          pip install -r requirements.txt

      - name: Créer un fichier log fictif
        run: |
          cd log-analyzer
          echo "[INFO] Start" > log.txt
          echo "[ERROR] Crash" >> log.txt
          echo "[WARNING] Slow response" >> log.txt
          echo "[INFO] Done" >> log.txt

      - name: Exécuter le script d'analyse
        run: |
          cd log-analyzer
          python log_analyzer.py --input log.txt --output rapport.txt
          cat rapport.txt

      - name: Vérifier le contenu du rapport
        run: |
          cd log-analyzer
          grep "INFO: 2" rapport.txt
          grep "ERROR: 1" rapport.txt
          grep "WARNING: 1" rapport.txt
